---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
      # - ["forwarded_port", {guest: 81, host: 8080}]
      - ["forwarded_port", {guest: 8081, host: 8081}]

suites:
  - name: default
    run_list:
      - recipe[myapache::default]
      - recipe[myhaproxy::default]
    attributes:
